=== unicode-org/unicodetools/unicodetools/src/main/resources/org/unicode/math/MathClassEx.dtd
<!ELEMENT mathchars (char+)>
<!ATTLIST mathchars
        unicode CDATA #REQUIRED
        tr25 CDATA #REQUIRED>

<!ELEMENT char EMPTY>
<!ATTLIST char
    cp CDATA #REQUIRED
    mathclass CDATA #IMPLIED
    note CDATA #IMPLIED
    deprecated CDATA #IMPLIED
    unassigned CDATA #IMPLIED
    equivalent CDATA #IMPLIED
>

=== unicode-org/unicodetools/unicodetools/src/main/resources/org/unicode/math/MathClassEx.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mathchars SYSTEM "MathClassEx.dtd">
<mathchars unicode="17.0" tr25="16">
   <char cp="0020" mathclass="S"/>
   <char cp="0021" mathclass="C" note="Factorial spacing"/>
   <char cp="0023" mathclass="N"/>
   <char cp="0024" mathclass="N"/>
   <char cp="0025" mathclass="N"/>
   <char cp="0026" mathclass="N"/>
   <char cp="0028" mathclass="O"/>
   <char cp="0029" mathclass="C"/>
   <char cp="002A" mathclass="N" note="[high, not /ast]"/>
   <char cp="002B" mathclass="V"/>
   <char cp="002C" mathclass="P"/>
   <char cp="002D" mathclass="N" note="(deprecated for math)"/>
   <char cp="002E" mathclass="P" note="period"/>
   <char cp="002F" mathclass="B" note="No extra spacing, stretchy"/>
   <char cp="0030" mathclass="N"/>
   <char cp="0031" mathclass="N"/>
   <char cp="0032" mathclass="N"/>
   <char cp="0033" mathclass="N"/>
   <char cp="0034" mathclass="N"/>
   <char cp="0035" mathclass="N"/>
   <char cp="0036" mathclass="N"/>
   <char cp="0037" mathclass="N"/>
   <char cp="0038" mathclass="N"/>
   <char cp="0039" mathclass="N"/>
   <char cp="003A" mathclass="P"/>
   <char cp="003B" mathclass="P"/>
   <char cp="003C" mathclass="R"/>
   <char cp="003D" mathclass="R"/>
   <char cp="003E" mathclass="R"/>
   <char cp="003F" mathclass="P"/>
   <char cp="0040" mathclass="N"/>
   <char cp="0041" mathclass="A"/>
   <char cp="0042" mathclass="A"/>
   <char cp="0043" mathclass="A"/>
   <char cp="0044" mathclass="A"/>
   <char cp="0045" mathclass="A"/>
   <char cp="0046" mathclass="A"/>
   <char cp="0047" mathclass="A"/>
   <char cp="0048" mathclass="A"/>
   <char cp="0049" mathclass="A"/>
   <char cp="004A" mathclass="A"/>
   <char cp="004B" mathclass="A"/>
   <char cp="004C" mathclass="A"/>
   <char cp="004D" mathclass="A"/>
   <char cp="004E" mathclass="A"/>
   <char cp="004F" mathclass="A"/>
   <char cp="0050" mathclass="A"/>
   <char cp="0051" mathclass="A"/>
   <char cp="0052" mathclass="A"/>
   <char cp="0053" mathclass="A"/>
   <char cp="0054" mathclass="A"/>
   <char cp="0055" mathclass="A"/>
   <char cp="0056" mathclass="A"/>
   <char cp="0057" mathclass="A"/>
   <char cp="0058" mathclass="A"/>
   <char cp="0059" mathclass="A"/>
   <char cp="005A" mathclass="A"/>
   <char cp="005B" mathclass="O"/>
   <char cp="005C" mathclass="B" note="No extra spacing, stretchy"/>
   <char cp="005D" mathclass="C"/>
   <char cp="005E" mathclass="N" note="TeX superscript operator"/>
   <char cp="005F" mathclass="N" note="TeX subscript operator"/>
   <char cp="0060" mathclass="D" note="Alias for 0300"/>
   <char cp="0061" mathclass="A"/>
   <char cp="0062" mathclass="A"/>
   <char cp="0063" mathclass="A"/>
   <char cp="0064" mathclass="A"/>
   <char cp="0065" mathclass="A"/>
   <char cp="0066" mathclass="A"/>
   <char cp="0067" mathclass="A"/>
   <char cp="0068" mathclass="A"/>
   <char cp="0069" mathclass="A"/>
   <char cp="006A" mathclass="A"/>
   <char cp="006B" mathclass="A"/>
   <char cp="006C" mathclass="A"/>
   <char cp="006D" mathclass="A"/>
   <char cp="006E" mathclass="A"/>
   <char cp="006F" mathclass="A"/>
   <char cp="0070" mathclass="A"/>
   <char cp="0071" mathclass="A"/>
   <char cp="0072" mathclass="A"/>
   <char cp="0073" mathclass="A"/>
   <char cp="0074" mathclass="A"/>
   <char cp="0075" mathclass="A"/>
   <char cp="0076" mathclass="A"/>
   <char cp="0077" mathclass="A"/>
   <char cp="0078" mathclass="A"/>
   <char cp="0079" mathclass="A"/>
   <char cp="007A" mathclass="A"/>
   <char cp="007B" mathclass="O"/>
   <char cp="007C" mathclass="F"/>
   <char cp="007D" mathclass="C"/>
   <char cp="007E" mathclass="N"/>
   <char cp="00A0" mathclass="S"/>
   <char cp="00A1" mathclass="P"/>
   <char cp="00A2" mathclass="N"/>
   <char cp="00A3" mathclass="N"/>
   <char cp="00A4" mathclass="N"/>
   <char cp="00A5" mathclass="N"/>
   <char cp="00A6" mathclass="N" note="(vertical)"/>
   <char cp="00A7" mathclass="N"/>
   <char cp="00A8" mathclass="D" note="/die, Alias for 0308"/>
   <char cp="00AC" mathclass="U" note="/neg /lnot"/>
   <char cp="00AF" mathclass="D" note="Alias for 0304"/>
   <char cp="00B0" mathclass="N"/>
   <char cp="00B1" mathclass="V"/>
   <char cp="00B2" mathclass="N"/>
   <char cp="00B3" mathclass="N"/>
   <char cp="00B4" mathclass="N" note="Alias for 0301"/>
   <char cp="00B5" mathclass="N"/>
   <char cp="00B6" mathclass="N" note="(paragraph sign)"/>
   <char cp="00B7" mathclass="B" note="/centerdot"/>
   <char cp="00B9" mathclass="N"/>
   <char cp="00BC" mathclass="N"/>
   <char cp="00BD" mathclass="N"/>
   <char cp="00BE" mathclass="N"/>
   <char cp="00BF" mathclass="P"/>
   <char cp="00D7" mathclass="B"/>
   <char cp="00F7" mathclass="B"/>
   <char cp="0131" mathclass="A"/>
   <char cp="0237" mathclass="A"/>
   <char cp="02C6" mathclass="D" note="Alias for 0302"/>
   <char cp="02C7" mathclass="D" note="Alias for 030C"/>
   <char cp="02D8" mathclass="D" note="Alias for 0306"/>
   <char cp="02D9" mathclass="D" note="Alias for 0307"/>
   <char cp="02DA" mathclass="D" note="Alias for 030A"/>
   <char cp="02DC" mathclass="D" note="Alias for 0303"/>
   <char cp="0300" mathclass="D" note="MathML prefers 0060"/>
   <char cp="0301" mathclass="D" note="MathML prefers 00B4"/>
   <char cp="0302" mathclass="D" note="MathML prefers 02C6"/>
   <char cp="0303" mathclass="D" note="MathML prefers 02DC"/>
   <char cp="0304" mathclass="D" note="MathML prefers 00AF"/>
   <char cp="0305" mathclass="D"/>
   <char cp="0306" mathclass="D" note="MathML prefers 02D8"/>
   <char cp="0307" mathclass="D" note="MathML prefers 02D9"/>
   <char cp="0308" mathclass="D" note="MathML prefers 00A8"/>
   <char cp="030A" mathclass="D" note="MathML prefers 02DA"/>
   <char cp="030C" mathclass="D" note="MathML prefers 02C7"/>
   <char cp="0311" mathclass="D"/>
   <char cp="0323" mathclass="D"/>
   <char cp="032C" mathclass="D"/>
   <char cp="032D" mathclass="D"/>
   <char cp="032E" mathclass="D"/>
   <char cp="032F" mathclass="D"/>
   <char cp="0330" mathclass="D"/>
   <char cp="0331" mathclass="D"/>
   <char cp="0332" mathclass="D"/>
   <char cp="0333" mathclass="D"/>
   <char cp="0338" mathclass="D" note="negation slash"/>
   <char cp="033A" mathclass="D"/>
   <char cp="033F" mathclass="D"/>
   <char cp="0346" mathclass="D"/>
   <char cp="0391" mathclass="A"/>
   <char cp="0392" mathclass="A"/>
   <char cp="0393" mathclass="A"/>
   <char cp="0394" mathclass="A"/>
   <char cp="0395" mathclass="A"/>
   <char cp="0396" mathclass="A"/>
   <char cp="0397" mathclass="A"/>
   <char cp="0398" mathclass="A"/>
   <char cp="0399" mathclass="A"/>
   <char cp="039A" mathclass="A"/>
   <char cp="039B" mathclass="A"/>
   <char cp="039C" mathclass="A"/>
   <char cp="039D" mathclass="A"/>
   <char cp="039E" mathclass="A"/>
   <char cp="039F" mathclass="A"/>
   <char cp="03A0" mathclass="A"/>
   <char cp="03A1" mathclass="A"/>
   <char cp="03A3" mathclass="A"/>
   <char cp="03A4" mathclass="A"/>
   <char cp="03A6" mathclass="A"/>
   <char cp="03A7" mathclass="A"/>
   <char cp="03A8" mathclass="A"/>
   <char cp="03A9" mathclass="A"/>
   <char cp="03B1" mathclass="A"/>
   <char cp="03B2" mathclass="A"/>
   <char cp="03B3" mathclass="A"/>
   <char cp="03B4" mathclass="A"/>
   <char cp="03B5" mathclass="A" note="rounded"/>
   <char cp="03B6" mathclass="A"/>
   <char cp="03B7" mathclass="A"/>
   <char cp="03B8" mathclass="A" note="straight theta"/>
   <char cp="03B9" mathclass="A"/>
   <char cp="03BA" mathclass="A"/>
   <char cp="03BB" mathclass="A"/>
   <char cp="03BC" mathclass="A"/>
   <char cp="03BD" mathclass="A"/>
   <char cp="03BE" mathclass="A"/>
   <char cp="03BF" mathclass="A"/>
   <char cp="03C0" mathclass="A"/>
   <char cp="03C1" mathclass="A"/>
   <char cp="03C3" mathclass="A"/>
   <char cp="03C4" mathclass="A"/>
   <char cp="03C5" mathclass="A"/>
   <char cp="03C6" mathclass="A" note="\varphi"/>
   <char cp="03C7" mathclass="A"/>
   <char cp="03C8" mathclass="A"/>
   <char cp="03C9" mathclass="A"/>
   <char cp="03D0" mathclass="A"/>
   <char cp="03D1" mathclass="A" note="\vartheta - curly or open small theta"/>
   <char cp="03D2" mathclass="A"/>
   <char cp="03D5" mathclass="A"/>
   <char cp="03D6" mathclass="A" note="rounded (pomega)"/>
   <char cp="03D8" mathclass="N"/>
   <char cp="03D9" mathclass="N"/>
   <char cp="03DA" mathclass="A" note="capital"/>
   <char cp="03DB" mathclass="A"/>
   <char cp="03DC" mathclass="A" note="capital"/>
   <char cp="03DD" mathclass="A" note="old"/>
   <char cp="03E0" mathclass="A" note="capital"/>
   <char cp="03E1" mathclass="A"/>
   <char cp="03F0" mathclass="A" note="rounded"/>
   <char cp="03F1" mathclass="A" note="rounded"/>
   <char cp="03F4" mathclass="A"/>
   <char cp="03F5" mathclass="A" note="straight"/>
   <char cp="03F6" mathclass="N"/>
   <char cp="0428" mathclass="A"/>
   <char cp="0606" mathclass="L"/>
   <char cp="0607" mathclass="L"/>
   <char cp="0608" mathclass="A"/>
   <char cp="0627" mathclass="A"/>
   <char cp="0628" mathclass="A"/>
   <char cp="0629" mathclass="A"/>
   <char cp="062A" mathclass="A"/>
   <char cp="062B" mathclass="A"/>
   <char cp="062C" mathclass="A"/>
   <char cp="062D" mathclass="A"/>
   <char cp="062E" mathclass="A"/>
   <char cp="062F" mathclass="A"/>
   <char cp="0630" mathclass="A"/>
   <char cp="0631" mathclass="A"/>
   <char cp="0632" mathclass="A"/>
   <char cp="0633" mathclass="A"/>
   <char cp="0634" mathclass="A"/>
   <char cp="0635" mathclass="A"/>
   <char cp="0636" mathclass="A"/>
   <char cp="0637" mathclass="A"/>
   <char cp="0638" mathclass="A"/>
   <char cp="0639" mathclass="A"/>
   <char cp="063A" mathclass="A"/>
   <char cp="1ACF" mathclass="D"/>
   <char cp="1AD0" mathclass="D"/>
   <char cp="1AD1" mathclass="D"/>
   <char cp="1AD2" mathclass="D"/>
   <char cp="1AD3" mathclass="D"/>
   <char cp="1AD4" mathclass="D"/>
   <char cp="1AD5" mathclass="D"/>
   <char cp="1AD6" mathclass="D"/>
   <char cp="1AD7" mathclass="D"/>
   <char cp="1AD8" mathclass="D"/>
   <char cp="1AD9" mathclass="D"/>
